export const CURRENT_START = "CURRENT_START";
export const CURRENT_SUCCESS = "CURRENT_SUCCESS";
export const CURRENT_FAILED = "CURRENT_FAILED";
export const CURRENT_UPDATE = "CURRENT_UPDATE";

export const SEVEN_DAYS_START = "SEVEN_DAYS_START";
export const SEVEN_DAYS_SUCCESS = "SEVEN_DAYS_SUCCESS";
export const SEVEN_DAYS_FAILED = "SEVEN_DAYS_FAILED";
export const SEVEN_DAYS_UPDATE = "SEVEN_DAYS_UPDATE";
